const COLOR_PALETTE = {
	PRIMARY_LIGHT: '#282975',
	PRIMARY_LIGHT_BG: '#282975',
	SECONDARY_LIGHT_BG: 'white',
	PRIMARY_LIGHT_TEXT: 'white',
	SECONDARY_LIGHT_TEXT: 'white',
	PRIMARY_BORDER_RADIUS: '5px',
	PRIMARY_LIGHT_BORDER: '#282975'
};

export const THEME = {
	BUTTON: {
		PRIM_COLOR: COLOR_PALETTE.PRIMARY_LIGHT_BG,
		PRIM_TEXT_COLOR: COLOR_PALETTE.PRIMARY_LIGHT_TEXT
	},
	DROPDOWN: {
		PRIM_BG_COLOR: COLOR_PALETTE.SECONDARY_LIGHT_BG,
		PRIM_TEXT_COLOR: COLOR_PALETTE.SECONDARY_LIGHT_TEXT,
		PRIM_BORDER_COLOR: COLOR_PALETTE.PRIMARY_LIGHT_BORDER,
		PRIM_BORDER_RADIUS: COLOR_PALETTE.PRIMARY_BORDER_RADIUS
	}
};