const THEME = {
	PRIMARY_COLOR: 'blue',
	SECONDARY_COLOR: 'green',
	PRIMARY_BG_COLOR: 'white',
	PRIMARY_TEXT_COLOR: 'white',
	SECONDARY_TEXT_COLOR: 'black',
	PRIMARY_BORDER_RADIUS: '5px'
};

export const STD_CSS_PROPS = {
	BTN_PRIM_COLOR: THEME.PRIMARY_COLOR,
	BTN_PRIM_TEXT_COLOR: THEME.PRIMARY_TEXT_COLOR,
	DROPDOWN_PRIM_BG_COLOR: THEME.PRIMARY_BG_COLOR,
	DROPDOWN_PRIM_TEXT_COLOR: THEME.SECONDARY_TEXT_COLOR,
	DROPDOWN_PRIM_BORDER_COLOR: 'blue',
	DROPDOWN_PRIM_BORDER_RADIUS: THEME.PRIMARY_BORDER_RADIUS
};