const COLOR_PALETTE = {
	PRIMARY_COLOR: 'blue',
	SECONDARY_COLOR: 'green',
	PRIMARY_BG_COLOR: 'white',
	PRIMARY_TEXT_COLOR: 'white',
	SECONDARY_TEXT_COLOR: 'black',
	PRIMARY_BORDER_RADIUS: '5px'
};

export const THEME = {
	BTN_PRIM_COLOR: COLOR_PALETTE.PRIMARY_COLOR,
	BTN_PRIM_TEXT_COLOR: COLOR_PALETTE.PRIMARY_TEXT_COLOR,
	DROPDOWN_PRIM_BG_COLOR: COLOR_PALETTE.PRIMARY_BG_COLOR,
	DROPDOWN_PRIM_TEXT_COLOR: COLOR_PALETTE.SECONDARY_TEXT_COLOR,
	DROPDOWN_PRIM_BORDER_COLOR: 'blue',
	DROPDOWN_PRIM_BORDER_RADIUS: COLOR_PALETTE.PRIMARY_BORDER_RADIUS
};